### ISSUE TITLE
integration not found in automation trigger

### ISSUE THREAD

**Issue by frank-ydf** [caiosweet/Home-Assistant-custom-components-INGV#15]
hi, I was trying your example automation but there is something wrong with the code:
`    trigger:
      - platform: geo_location
        source: "ingv_centro_nazionale_terremoti"`
the trigger is not recognized... source "ingv..." says INTEGRATION NOT FOUND.
Did you have some suggestion? 
card and all other things works perfectly!

**Comment by caiosweet** [comment]
Hello.  This is a custom component, it must be installed manually or via HACS.  In the documentation I see that I have not entered how to install the component😝 Do you use [HACS?](https://github.com/hacs/integration)

**Comment by frank-ydf** [comment]
Caio you did a grat job, also without that missed up in documentation!
I installed the component in HACS (via the GUI) and edited the config file manually as your instructions and examples.
I already written down the geolocation:

`# INGV TERREMOTI LOCATION
geo_location:
  - platform: ingv_centro_nazionale_terremoti
    radius: 100
    minimum_magnitude: 2.0`

and inserted the zone "geoalarm" in the gui (also tried in the config.yaml... but not both at the same time, obviously).
I don't know if the problem is due to a newer version of HA or something else, anyway, I saw in the automation visual editor that the trigger platform "GEO_LOCATION" don't exist (anymore maybe?).

Se vuoi possiamo parlarne in italiano per una miglior comprensione, felice di aiutarti per quel che posso
Francesco

**Comment by frank-ydf** [comment]
Ciao Caio, yes I installed via HACS gui (clicked on "install").
Custom card works flawlessly (with your code and tried also with my code to match my personalization) but in automation there is the error on trigger "Integration not found".

Se vuoi possiamo continuare in italiano, felice di aiutarti il piu' possibile

**Comment by frank-ydf** [comment]
sorry Caio, that was a "fake" issue: a problem on spotify integration made all those errors on automation. 
Thanks!
