### ISSUE TITLE
wrong link in README.md

### ISSUE THREAD

**Issue by gpongelli** [caiosweet/Home-Assistant-custom-components-INGV#16]
The link "Other Information" into README.md is wrong , working link is [this one](https://hassiohelp.eu/2019/10/06/home-assistant-package-eventi-naturali/) .

Thanks.

**Comment by caiosweet** [comment]
Thank you. Next update I'll fix the link and also some examples.

**Comment by caiosweet** [comment]
Fixed. :0)
