### ISSUE TITLE
INSTALLATION ERROR ON HOME ASSISTANT CORE ON SYNOLOGY NAS DSM 7

### ISSUE THREAD

**Issue by Pippodomotic** [caiosweet/Home-Assistant-custom-components-INGV#18]
Hi, the custom component "Home-Assistant-custom-components-INGV" is very interesting. I tried to install it via HACS and I cofigured the configuration.yalm file as per your instructions. But I get this error: "Platform error geo_location.ingv_centro_nazionale_terquoti - Requirements for ingv_centro_nazionale_terquoti not found: ['georss-ingv-centro-Nazionale-earthquakes-client == 0.5']."
I tried to install georss-ingv-national-center-earthquakes-client == 0.5 via: pip install georss-ingv-national-center-earthquakes-client == 0.5 but I get an error also in this case.
How can I proceed?
I use Home Assistant Core on Synology Nas DSM 7.
Thank you

**Comment by caiosweet** [comment]
Hi.

**Comment by Pippodomotic** [comment]
Hi, I followed your instructions perfectly but I keep getting this message that does not allow me to restart Home assistant: "Requirements for ingv_centro_nazionale_terremoti not found: ['georss-ingv-centro-Nazionale-earthquakes-client == 0.5']." It seems that required component is missing but I cannot install it.

**Comment by caiosweet** [comment]
Uhmm. 
I don't use HA core in a NAS, but I tried HA Core with virtual env and I don't have any requirements issues. The same goes for HassOs, Supervised and container...

I cannot replicate the problem. 
Try deleting the folder or uninstalling from Hacs, clearing the configuration and retrying the above procedure after a reboot.

Do you have other custom components installed or is it the first?

**Comment by Pippodomotic** [comment]
Yes, I have other custom components installed through Hacs and they work (not all the ones I've tried to install have worked).
I also installed "DPC Civil Protection Department" (also this very nice and interesting integration) which works but not perfectly because I get a permanent notification from Home Assistant that says:

"Logger: homeassistant.setup
Source: setup.py:317
First occurred: 22:04:20 (1 occurrences)
Last logged: 22:04:20

Unable to prepare setup for platform dpc.binary_sensor: Platform not found (cannot import name 'BinarySensorDeviceClass' from 'homeassistant.components.binary_sensor' (/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant /components/binary_sensor/__init__.py)).

**Comment by caiosweet** [comment]
What version of Home Assistant do you have installed?

In the [HA Core](https://www.home-assistant.io/installation/generic-x86-64#install-home-assistant-core) installation notes I see that it takes Python 3.9 but in your log I see 3.8.

Try updating your system and see if it fixes these problems.

For DPC the last update must be done only if you have HA 2021.12.x installed.

**Comment by Pippodomotic** [comment]
Hello
I did some tests.
1) I installed DPC version 2021.8.1 and it works without giving errors: I got 1 Device and 8 entities (with the latest version I only got 2 entities)
2) for INGV unfortunately I can't proceed even trying to install previous versions. I think the problem is in the python module which I can't install via "pip install georss-ingv-national-center-earthquakes-client == 0.5"
I currently have Python 3.10 installed on my Synology.

P.S .:
for DPC, how can I view the "Cards: card-mod, markdown" like the ones you can see from your "From my Natural Events project" information?

Thanks and congratulations on your Home Assistant integrations.

**Comment by caiosweet** [comment]
> I installed DPC version 2021.8.1 and it works without giving errors: I got 1 Device and 8 entities (with the latest version I only got 2 entities)

Correct. 
The latest update is only for those who have installed version 2021.12.0 or higher.

> I think the problem is in the python module..

You need to investigate your system. With HACS, requirements are installed automatically via the _manifest.json_ file. 
Check the pip Version and Verify the Installation. Maybe try using pip3 instead of pip.
This component I can say that works and tested with HassOs, Supervised, Docker Container and Virtual Environment.
I have no way to test the component with the type of Home Assistant installation you did.

> for DPC, how can I view the "Cards: card-mod, markdown" like the ones you can see from your "From my Natural Events project" information?

it is a card that is part of a more complex one, inherent to another complex project. The part is [this](https://github.com/caiosweet/Package-Natural-Events/blob/16198ee8e7f75b35266810996eff27fe495c2ef1/config/lovelace/cards/card_natural_events_light.yaml#L411)

You should also provide more specific data. What version of HA do you have? What HACS version? Maybe my component is not compatible with older versions.

**Comment by caiosweet** [comment]
You solved?  The author added support for python 10 maybe that was the problem?  I have updated the library to the latest version.

**Comment by caiosweet** [comment]
A new version has come out, with a new library. this problem is out of date.
