### ISSUE TITLE
deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by heinemannj** [caiosweet/Home-Assistant-custom-components-INGV#27]
`LENGTH_MILES was used from ingv_centro_nazionale_terremoti, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please create a bug report at https://github.com/caiosweet/Home-Assistant-custom-components-INGV/issues`

```
LENGTH_KILOMETERS was used from ingv_centro_nazionale_terremoti, this is a deprecated constant which will be removed in HA Core 2025.1.
Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/caiosweet/Home-Assistant-custom-components-INGV/issues
```

**Comment by MarcoZ76** [comment]
I have this issue too

**Comment by riddik14** [comment]
stesso problema

**Comment by caiosweet** [comment]
I think that with the changes in @mrai64, the warning has been resolved.
