### ISSUE TITLE
Link immagini

### ISSUE THREAD

**Issue by andreamag00** [caiosweet/Home-Assistant-custom-components-INGV#31]
**Describe the bug**

Credo che sia cambiato il link per ottenere l'immagine della mappa di ciascun terremoto.

**To Reproduce**

Per verificare il link che viene attualmente fornito dall'integrazione basta aprire i dettagli di un terremoto, come nell'immagine sottostante:
<img width="561" alt="Screenshot 2024-08-08 alle 10 33 50" src="https://github.com/user-attachments/assets/5d919d61-01cc-4f7d-957f-b6fc2ff5058f">

Il link fornito attualmente dall'integrazione è il seguente:
`http://shakemap.rm.ingv.it/shake4/data/39998141/current/products/intensity.jpg`
Se si prova ad aprire detto link si vede che non funziona.

Il link attualmente corretto per ottenere la mappa di detto terremoto, invece, è il seguente:
`https://shakemap.ingv.it/data/39998141/current/products/intensity.jpg`
Se si prova ad aprire detto link si vede che funziona correttamente.

**Conclusion**
Credo che sia necessario aggiornare la struttura del link fornito dall'integrazione, in quanto sembra essere cambiata la struttura del link per ottenere l'immagine di ciascun terremoto su shakemap.ingv.it

Grazie mille

Ciao

**Comment by caiosweet** [comment]
Grazie mille. ho inserito il nuovo link (rel. 2024.08.0). Poi, tempo permettendo dovrò fare altri aggiornamenti (vedi duplice notifica).
