### ISSUE TITLE
Example of lovelace card?

### ISSUE THREAD

**Issue by mfabiani53** [caiosweet/Home-Assistant-custom-components-INGV#6]
Can you show us an example about how to configure a lovelace card with this component?
I see many new sensors created so i think i need only an entities card or not? And how to show a map?

**Comment by legolas0802** [comment]
inside the zip file you will find all the cards you need

**Comment by sajikur** [comment]
need more informations about lovelace integration. Thanx

**Comment by legolas0802** [comment]
what are the entities to use in Lovelace?

**Comment by sajikur** [comment]
No entities. I see notification in attach that change on every new event

In data 23 novembre 2020 16:31:45 legolas0802 <notifications@github.com> ha 
scritto:

**Comment by caiosweet** [comment]
I have published a new version. Added more examples and useful links.

**Comment by sajikur** [comment]
Thanx

In data 23 novembre 2020 19:47:29 caiosweet <notifications@github.com> ha 
scritto:
